name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2

  cupertino_icons: ^0.1.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
